### ISSUE TITLE
.deb doesn't quite work

### ISSUE THREAD

**Issue by grinapo** [arineng/nicinfo#16]
$ nicinfo 

```
/usr/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'nicinfo' (>= 0) among 13 total gem(s) (Gem::LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
        from /usr/bin/nicinfo:22:in `<main>'

```

**Comment by anewton1998** [comment]
FPM was used to create the .deb, so I'm not sure what magic it needs. What Linux distribution are you using?

**Comment by grinapo** [comment]
Surprisingly Debian. :-) More precisely Debian/sid. Probably the deb is pretty much broken but 
 I'm not a Ruby guy 
 I cannot tell how and why.

**Comment by anewton1998** [comment]
So I looked into this. FPM is actually doing some things that will never work for cross-distribution packages. The only way to get it to work is to have a much, much fancier build system with docker or VMs creating an OS package. And even then, all FPM is doing is taking the files created by `gem` and laying them down on the filesystem. A person is actually better off using `gem` or `bundler` because that will do true dependency resolution.

Therefore the right thing to do is to remove the separate OS packages and instruct installation to be done via `gem`. I'll work on getting a decent `gem` and `bundler` setup so that is a much better process.
